services:
  app:
    image: 'docker.io/best_insurance/api:latest'
    container_name: app
    depends_on:
      db:
        condition: service_started
      oauth:
        condition: service_started
    ports:
      - '8080:8080'
      - '5005:5005'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
      - EVENTLISTENER_QUEUE_NAME=subscriptionLogQueue
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=5005
      - BPL_DEBUG_SUSPEND=false
        #FOARTE IMPORTANT PENTRU SWAGGER-UI
      - SPRINGDOC_API_DOCS_VERSION=OPENAPI_3_0
        #Asta e pentru SampleDataLoader
      - DATALOADER_LOADSAMPLE=true
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://oauth:9090
      - SPRINGDOC_SWAGGER_UI_OAUTH_CLIENTID=api-client
      - SPRINGDOC_SWAGGER_UI_OAUTH_CLIENTSECRET=secret
      - SPRINGDOC_OAUTHFLOW_AUTHORIZATIONURL=http://127.0.0.1:9090/oauth2/authorize
      - SPRINGDOC_OAUTHFLOW_TOKENURL=http://127.0.0.1:9090/oauth2/token
      - SPRINGDOC_SWAGGER_UI_OAUTH_REDIRECT_URL=http://127.0.0.1:8080/swagger-ui/oauth2-redirect.html

  oauth:
    image: 'oauth2server:latest'
    build:
      context: .
      dockerfile: Dockerfile.oauth2TestServer
    container_name: oauth
    hostname: auth-server
    ports:
      - '9090:9090'
    environment:
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY=DEBUG
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB=DEBUG
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_OAUTH2=DEBUG

  db:
    image: 'postgres:15.4-alpine'
    container_name: db
    ports:
      - '55432:5432'
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
      - POSTGRES_DB=compose-postgres